import type { ReactNode } from "react";
import Link from "next/link";
import { ToolCTA } from "@/components/BlogLayout";
import type { BlogContent } from "./index";

export const content: BlogContent = {
  en: (
    <>
      <aside aria-label="Summary" className="bg-zinc-800/50 border border-zinc-700 rounded-xl p-5 mb-8">
        <p><strong>TL;DR:</strong> Length beats complexity. A random 16+ character password is stronger than "P@ssw0rd!" ever will be. Use a unique password for every account, store them in a password manager, and turn on two-factor authentication. Generate random passwords locally in your browser — never send them to a server.</p>
      </aside>

      <section>
        <h2>What Makes a Password Strong?</h2>
        <p>Password strength comes from <strong>entropy</strong> — how many guesses an attacker needs. Entropy grows with length and randomness, not with clever substitutions. Swapping "a" for "@" adds almost nothing, because cracking tools try those substitutions first.</p>
        <ul>
          <li><strong>Length:</strong> 16 characters or more. Each additional character multiplies the search space.</li>
          <li><strong>Randomness:</strong> Generated by a computer, not your brain. Humans are terrible at randomness.</li>
          <li><strong>Uniqueness:</strong> A different password for every account, so one breach can't cascade.</li>
        </ul>
        <p>The <a href="https://pages.nist.gov/800-63-3/sp800-63b.html" target="_blank" rel="noopener noreferrer" className="text-blue-400 hover:text-blue-300">NIST digital identity guidelines</a> agree: long, memorable-but-random passphrases beat short complex ones, and forced periodic rotation often makes passwords weaker.</p>
      </section>

      <section>
        <h2>Why Password Reuse Is the Real Danger</h2>
        <p>Most account takeovers don't involve cracking anything. Attackers take username and password pairs leaked from one site and try them everywhere else — a technique called credential stuffing. If your email password is also your forum password, one leaked database hands over your inbox.</p>
        <p>The fix is simple: never reuse a password. A password manager makes this effortless — you only memorize one master passphrase and let it generate and remember the rest.</p>
      </section>

      <section>
        <h2>Password Managers and Passkeys</h2>
        <p>A password manager stores your credentials in an encrypted vault. Reputable ones use zero-knowledge encryption: even the vendor can't read your vault. This is far safer than a note file, your browser's plain password list, or the same password everywhere.</p>
        <p>Where available, enable <strong>passkeys</strong> — cryptographic logins bound to your device that replace passwords entirely. They're phishing-resistant and can't be reused or leaked in a database dump.</p>
        <ul>
          <li>Protect the manager itself with a long passphrase and two-factor authentication.</li>
          <li>Export and back up your vault periodically.</li>
          <li>On shared computers, never save credentials in the browser.</li>
        </ul>
      </section>

      <section>
        <h2>Generate Strong Passwords for Free</h2>
        <p>Our <Link href="/tools/password-generator" className="text-blue-400 hover:text-blue-300">Password Generator</Link> creates random passwords and passphrases with configurable length and character sets. It runs entirely in your browser — generated passwords never leave your device. Check any existing password with the <Link href="/tools/password-strength" className="text-blue-400 hover:text-blue-300">Password Strength Checker</Link> to see how long it would survive a brute-force attack.</p>
        <ToolCTA name="Password Generator" href="/tools/password-generator" description="Create random passwords and passphrases with custom length and character sets. Runs entirely in your browser — nothing is sent to any server." />
      </section>
    </>
  ),

  zh: (
    <>
      <aside aria-label="摘要" className="bg-zinc-800/50 border border-zinc-700 rounded-xl p-5 mb-8">
        <p><strong>太长不看：</strong>长度胜过复杂度。16 位以上的随机密码远比 "P@ssw0rd!" 这类密码安全。每个账户用独立密码，存入密码管理器，并开启两步验证。在浏览器本地生成随机密码——绝不发送到任何服务器。</p>
      </aside>

      <section>
        <h2>什么样的密码才算强密码？</h2>
        <p>密码强度来自<strong>熵</strong>——攻击者需要尝试的次数。熵随长度和随机性增长，而不是靠花哨的替换。把 "a" 换成 "@" 几乎没有帮助，因为破解工具会最先尝试这类替换。</p>
        <ul>
          <li><strong>长度：</strong>至少 16 个字符。每多一位都会让搜索空间成倍增长。</li>
          <li><strong>随机性：</strong>由计算机生成，而不是人脑。人类非常不擅长随机。</li>
          <li><strong>唯一性：</strong>每个账户使用不同密码，避免一处泄露殃及全部。</li>
        </ul>
        <p><a href="https://pages.nist.gov/800-63-3/sp800-63b.html" target="_blank" rel="noopener noreferrer" className="text-blue-400 hover:text-blue-300">NIST 数字身份指南</a>也持相同观点：长而随机、易于记忆的密码短语胜过短而复杂的密码；强制定期换密码反而往往让密码变弱。</p>
      </section>

      <section>
        <h2>为什么密码复用才是真正的危险</h2>
        <p>大多数账户被盗并不是因为密码被破解。攻击者把某个网站泄露的用户名密码对拿到其他网站批量尝试——这叫“撞库”。如果你的邮箱密码和论坛密码相同，一次数据库泄露就等于交出了你的收件箱。</p>
        <p>解决办法很简单：绝不复用密码。密码管理器让这件事毫不费力——你只需记住一个主密码短语，其余的交给它生成和记忆。</p>
      </section>

      <section>
        <h2>密码管理器与通行密钥</h2>
        <p>密码管理器把凭据存进加密保险库。正规产品采用零知识加密：连厂商也无法读取你的保险库。这远比记事本、浏览器明文密码列表或到处使用同一个密码安全。</p>
        <p>在支持的网站开启<strong>通行密钥（Passkey）</strong>——绑定设备的加密登录方式，可以完全替代密码。它天然防钓鱼，也不会在数据库泄露中被盗用。</p>
        <ul>
          <li>用长密码短语和两步验证保护密码管理器本身。</li>
          <li>定期导出并备份你的保险库。</li>
          <li>在公用电脑上，绝不把凭据保存在浏览器里。</li>
        </ul>
      </section>

      <section>
        <h2>免费生成强密码</h2>
        <p>我们的<Link href="/tools/password-generator" className="text-blue-400 hover:text-blue-300">密码生成器</Link>可以生成可配置长度和字符集的随机密码与密码短语。它完全在浏览器中运行——生成的密码绝不离开你的设备。还可以用<Link href="/tools/password-strength" className="text-blue-400 hover:text-blue-300">密码强度检测</Link>检查现有密码，看看它能扛多久暴力破解。</p>
        <ToolCTA name="密码生成器" href="/tools/password-generator" description="生成自定义长度和字符集的随机密码与密码短语。完全在浏览器中运行——不向任何服务器发送数据。" />
      </section>
    </>
  ),

  ja: (
    <>
      <aside aria-label="要約" className="bg-zinc-800/50 border border-zinc-700 rounded-xl p-5 mb-8">
        <p><strong>要約：</strong>長さは複雑さに勝ります。16 文字以上のランダムなパスワードは "P@ssw0rd!" のようなパスワードよりはるかに強力です。アカウントごとに異なるパスワードを使い、パスワードマネージャーで管理し、二要素認証を有効にしましょう。パスワードはブラウザ内でローカル生成し、サーバーには決して送らないこと。</p>
      </aside>

      <section>
        <h2>強力なパスワードの条件とは？</h2>
        <p>パスワードの強度は<strong>エントロピー</strong>——攻撃者が必要とする試行回数——で決まります。エントロピーは長さとランダム性で増え、巧妙な文字置換では増えません。"a" を "@" に変えてもほぼ無意味です。破解ツールはまずそのような置換を試すからです。</p>
        <ul>
          <li><strong>長さ：</strong>16 文字以上。1 文字増えるごとに探索空間が倍増します。</li>
          <li><strong>ランダム性：</strong>人間ではなくコンピューターが生成したもの。人間はランダム性が苦手です。</li>
          <li><strong>一意性：</strong>アカウントごとに異なるパスワードで、1 件の漏洩が連鎖しないようにします。</li>
        </ul>
        <p><a href="https://pages.nist.gov/800-63-3/sp800-63b.html" target="_blank" rel="noopener noreferrer" className="text-blue-400 hover:text-blue-300">NIST のデジタル ID ガイドライン</a>も同様で、長くて覚えやすいランダムなパスフレーズが短く複雑なパスワードに勝り、強制された定期変更はむしろパスワードを弱くしがちだと述べています。</p>
      </section>

      <section>
        <h2>パスワード使い回しが本当の危険</h2>
        <p>アカウント乗っ取りの多くは、パスワードの解析ではなく「cred stuffing（認証情報の流用）」で起きます。あるサイトから漏れた ID とパスワードの組み合わせを、他のサービスで片っ端から試す手法です。メールのパスワードと掲示板のパスワードが同じなら、1 件の漏洩で受信箱ごと奪われます。</p>
        <p>解決策はシンプル：パスワードを使い回さないこと。パスワードマネージャーなら、覚えるのはマスターパスフレーズ 1 つで、あとは生成と記憶を任せられます。</p>
      </section>

      <section>
        <h2>パスワードマネージャーとパスキー</h2>
        <p>パスワードマネージャーは認証情報を暗号化された保管庫に保存します。信頼できる製品はゼロ知識暗号を採用しており、ベンダー自身も保管庫を読めません。メモ書きやブラウザの平文リスト、どこか 1 つの使い回しよりはるかに安全です。</p>
        <p>対応サービスでは<strong>パスキー</strong>を有効にしましょう。デバイスに紐づく暗号化的なログイン方式で、パスワードを完全に置き換えます。フィッシングに強く、データベース漏洩で盗まれることもありません。</p>
        <ul>
          <li>マネージャー自体は長いパスフレーズと二要素認証で保護する。</li>
          <li>保管庫は定期的にエクスポートしてバックアップする。</li>
          <li>共用 PC ではブラウザに認証情報を保存しない。</li>
        </ul>
      </section>

      <section>
        <h2>無料で強力なパスワードを生成</h2>
        <p>当サイトの<Link href="/tools/password-generator" className="text-blue-400 hover:text-blue-300">パスワード生成ツール</Link>は、長さと文字種を指定してランダムなパスワードやパスフレーズを生成します。完全にブラウザ内で動作し、生成されたパスワードがデバイスの外に出ることはありません。既存のパスワードは<Link href="/tools/password-strength" className="text-blue-400 hover:text-blue-300">パスワード強度チェッカー</Link>で確認し、総当たり攻撃にどれくらい耐えられるか見てみましょう。</p>
        <ToolCTA name="パスワード生成ツール" href="/tools/password-generator" description="長さと文字種をカスタマイズしたランダムパスワード・パスフレーズを生成。完全にブラウザ内で動作し、サーバーには何も送信されません。" />
      </section>
    </>
  ),

  ko: (
    <>
      <aside aria-label="요약" className="bg-zinc-800/50 border border-zinc-700 rounded-xl p-5 mb-8">
        <p><strong>요약:</strong> 길이가 복잡성을 이깁니다. 16자 이상의 무작위 비밀번호는 "P@ssw0rd!" 같은 비밀번호보다 훨씬 강력합니다. 계정마다 다른 비밀번호를 쓰고, 비밀번호 관리자에 보관하며, 2단계 인증을 켜세요. 비밀번호는 브라우저에서 로컬로 생성하고 절대 서버로 보내지 마세요.</p>
      </aside>

      <section>
        <h2>강력한 비밀번호의 조건은?</h2>
        <p>비밀번호 강도는 <strong>엔트로피</strong>——공격자가 필요한 시도 횟수——에서 나옵니다. 엔트로피는 길이와 무작위성으로 커지며, 영리한 치환으로는 늘어나지 않습니다. "a"를 "@"로 바꾸는 것은 거의 무의미합니다. 해킹 도구가 가장 먼저 시도하는 치환이기 때문입니다.</p>
        <ul>
          <li><strong>길이:</strong> 16자 이상. 한 글자가 늘 때마다 탐색 공간이 배가됩니다.</li>
          <li><strong>무작위성:</strong> 사람의 머리가 아니라 컴퓨터가 생성한 것. 인간은 무작위성에 매우 서툽니다.</li>
          <li><strong>고유성:</strong> 계정마다 다른 비밀번호를 써서 한 곳의 유출이 연쇄되지 않게 합니다.</li>
        </ul>
        <p><a href="https://pages.nist.gov/800-63-3/sp800-63b.html" target="_blank" rel="noopener noreferrer" className="text-blue-400 hover:text-blue-300">NIST 디지털 ID 가이드라인</a>도 같은 입장입니다. 길고 기억하기 쉬운 무작위 패스프레즈가 짧고 복잡한 비밀번호보다 낫고, 강제적인 주기적 변경은 오히려 비밀번호를 약하게 만들기 쉽다고 말합니다.</p>
      </section>

      <section>
        <h2>비밀번호 재사용이 진짜 위험</h2>
        <p>대부분의 계정 탈취는 비밀번호를 깨는 것이 아닙니다. 공격자는 한 사이트에서 유출된 아이디·비밀번호 조합을 다른 서비스에 무차별 대입합니다. 이메일 비밀번호와 커뮤니티 비밀번호가 같다면, 데이터베이스 유출 한 번으로 수신함 전체를 내주는 셈입니다.</p>
        <p>해결책은 간단합니다: 비밀번호를 재사용하지 않기. 비밀번호 관리자라면 이 일이 수월해집니다. 마스터 패스프레즈 하나만 외우고 나머지는 생성과 기억을 맡기면 됩니다.</p>
      </section>

      <section>
        <h2>비밀번호 관리자와 패스키</h2>
        <p>비밀번호 관리자는 자격 증명을 암호화된 금고에 보관합니다. 신뢰할 수 있는 제품은 제로 지식 암호화를 사용해 벤더조차 금고를 읽을 수 없습니다. 메모장이나 브라우저의 평문 목록, 한 곳에만 쓰는 같은 비밀번호보다 훨씬 안전합니다.</p>
        <p>지원하는 서비스에서는 <strong>패스키</strong>를 켜세요. 기기에 바인딩되는 암호학적 로그인 방식으로 비밀번호를 완전히 대체합니다. 피싱에 강하고 데이터베이스 유출로 도난될 수도 없습니다.</p>
        <ul>
          <li>관리자 자체는 긴 패스프레즈와 2단계 인증으로 보호하세요.</li>
          <li>금고는 주기적으로 내보내기해 백업하세요.</li>
          <li>공용 PC에서는 브라우저에 자격 증명을 저장하지 마세요.</li>
        </ul>
      </section>

      <section>
        <h2>무료로 강력한 비밀번호 생성</h2>
        <p>당사의 <Link href="/tools/password-generator" className="text-blue-400 hover:text-blue-300">비밀번호 생성기</Link>는 길이와 문자 집합을 지정해 무작위 비밀번호와 패스프레즈를 만듭니다. 완전히 브라우저 안에서 동작하며 생성된 비밀번호는 기기를 떠나지 않습니다. 기존 비밀번호는 <Link href="/tools/password-strength" className="text-blue-400 hover:text-blue-300">비밀번호 강도 검사기</Link>로 확인해 무차별 대입 공격을 얼마나 버티는지 살펴보세요.</p>
        <ToolCTA name="비밀번호 생성기" href="/tools/password-generator" description="길이와 문자 집합을 커스터마이즈한 무작위 비밀번호·패스프레즈 생성. 완전히 브라우저에서 동작하며 서버로는 아무것도 전송되지 않습니다." />
      </section>
    </>
  ),

  faqs: {
    en: [
      { question: "What makes a password strong?", answer: "Length, randomness, and uniqueness. Use at least 16 random characters (or a 4-5 word passphrase), generated by a computer, and never reuse it on another account. Length matters more than symbol substitutions like swapping 'a' for '@'." },
      { question: "Are password managers safe?", answer: "Yes — reputable managers use zero-knowledge encryption, so even the vendor cannot read your vault. They are far safer than reusing passwords or storing them in plain text. Protect the manager with a long master passphrase and two-factor authentication." },
      { question: "How often should I change my passwords?", answer: "Current guidance, including NIST SP 800-63B, recommends changing a password only when there is evidence of compromise — not on a fixed schedule. Forced rotation leads to weaker, predictable patterns like 'Password1', 'Password2'." },
    ],
    zh: [
      { question: "什么样的密码才算强密码？", answer: "长度、随机性和唯一性。至少使用 16 个随机字符（或 4-5 个词的密码短语），由计算机生成，且绝不在其他账户上复用。长度比把 'a' 换成 '@' 这类符号替换重要得多。" },
      { question: "密码管理器安全吗？", answer: "安全。正规的管理器采用零知识加密，连厂商也无法读取你的保险库。这比复用密码或明文存储安全得多。用长主密码短语和两步验证保护管理器本身即可。" },
      { question: "密码应该多久换一次？", answer: "包括 NIST SP 800-63B 在内的现行指南建议：只在有泄露迹象时更换密码，而不是定期强制更换。强制轮换反而催生 'Password1'、'Password2' 这类可预测的弱模式。" },
    ],
    ja: [
      { question: "強力なパスワードの条件は？", answer: "長さ・ランダム性・一意性です。最低 16 文字のランダムな文字列（または 4〜5 語のパスフレーズ）をコンピューターに生成させ、他のアカウントで使い回さないこと。'a' を '@' にするような置換より長さの方がはるかに重要です。" },
      { question: "パスワードマネージャーは安全ですか？", answer: "はい。信頼できる製品はゼロ知識暗号化を採用しており、ベンダーにも保管庫を読めません。使い回しや平文保存よりはるかに安全です。マネージャー自体は長いマスターパスフレーズと二要素認証で保護しましょう。" },
      { question: "パスワードはどのくらいの頻度で変えるべき？", answer: "NIST SP 800-63B を含む現行ガイドラインでは、定期的な強制変更ではなく「漏洩の兆候があるときのみ」変更を推奨しています。強制ローテーションは 'Password1', 'Password2' のような予測しやすい弱いパターンを生みがちです。" },
    ],
    ko: [
      { question: "강력한 비밀번호의 조건은 무엇인가요?", answer: "길이, 무작위성, 고유성입니다. 최소 16자의 무작위 문자열(또는 4-5단어 패스프레즈)을 컴퓨터로 생성하고 다른 계정에 재사용하지 마세요. 'a'를 '@'로 바꾸는 치환보다 길이가 훨씬 중요합니다." },
      { question: "비밀번호 관리자는 안전한가요?", answer: "네. 신뢰할 수 있는 관리자는 제로 지식 암호화를 사용해 벤더조차 금고를 읽을 수 없습니다. 재사용이나 평문 저장보다 훨씬 안전합니다. 관리자 자체는 긴 마스터 패스프레즈와 2단계 인증으로 보호하세요." },
      { question: "비밀번호는 얼마나 자주 바꿔야 하나요?", answer: "NIST SP 800-63B 등 현행 가이드라인은 주기적 강제 변경이 아니라 '유출 징후가 있을 때만' 변경을 권고합니다. 강제 순환은 'Password1', 'Password2' 같은 예측 가능한 약한 패턴을 낳기 쉽습니다." },
    ],
  },
};
