import type { MetadataRoute } from "next";
import { blogPostsMeta } from "@/data/blog-posts";

const locales = ["en", "zh", "ja", "ko"] as const;

const tools = [
  "video-watermark-remover",
  "photo-watermark-remover",
  "qr-code-generator",
  "qr-code-reader",
  "face-detector",
  "color-palette-generator",
  "css-gradient-generator",
  "box-shadow-generator",
  "password-generator",
  "json-formatter",
  "base64-encoder",
  "lorem-ipsum-generator",
  "uuid-generator",
  "word-counter",
  "image-color-picker",
  "screen-color-picker",
  "aspect-ratio-calculator",
  "unit-converter",
  "regex-tester",
  "markdown-preview",
  "fancy-text-generator",
  "image-compressor",
  "image-resizer",
  "background-remover",
  "diff-checker",
  "glassmorphism-generator",
  "css-clip-path",
  "css-loader-generator",
  "html-minifier",
  "css-minifier",
  "js-minifier",
  "favicon-generator",
  "multiavatar-avatar-generator",
  "color-contrast-checker",
  "text-case-converter",
  "timestamp-converter",
  "hash-generator",
  "jwt-decoder",
  "url-encoder",
  "cron-generator",
  "svg-blob-generator",
  "svg-wave-generator",
  "image-to-base64",
  "barcode-generator",
  "html-entity-encoder",
  "chmod-calculator",
  "color-shades-generator",
  "image-crop",
  "meta-tag-generator",
  "robots-txt-generator",
  "neumorphism-generator",
  "json-to-csv",
  "placeholder-image",
  "css-text-shadow",
  "css-flexbox",
  "css-grid",
  "invoice-generator",
  "url-slug-generator",
  "url-shortener",
  "exif-viewer",
  "noise-generator",
  "og-preview",
  "css-border-radius",
  "color-converter",
  "html-table-generator",
  "css-cubic-bezier",
  "bionic-reading",
  "css-background-pattern",
  "image-filters",
  "json-validator",
  "pixel-art",
  "mortgage-calculator",
  "compound-interest-calculator",
  "loan-calculator",
  "percentage-calculator",
  "tip-calculator",
  "salary-calculator",
  "auto-loan-calculator",
  "retirement-calculator",
  "savings-calculator",
  "investment-calculator",
  "bmi-calculator",
  "calorie-calculator",
  "tdee-calculator",
  "body-fat-calculator",
  "macro-calculator",
  "profit-margin-calculator",
  "discount-calculator",
  "sales-tax-calculator",
  "roi-calculator",
  "age-calculator",
  "payment-calculator",
  "paycheck-calculator",
  "interest-calculator",
  "inflation-calculator",
  "401k-calculator",
  "amortization-calculator",
  "income-tax-calculator",
  "debt-payoff-calculator",
  "hourly-to-salary-calculator",
  "budget-calculator",
  "simple-interest-calculator",
  "net-worth-calculator",
  "stock-profit-calculator",
  "credit-card-payoff-calculator",
  "down-payment-calculator",
  "dividend-calculator",
  "fire-calculator",
  "vat-calculator",
  "break-even-calculator",
  "mortgage-affordability-calculator",
  "apr-calculator",
  "student-loan-calculator",
  "capital-gains-tax-calculator",
  "gpa-calculator",
  "grade-calculator",
  "random-number-generator",
  "countdown-timer",
  "stopwatch",
  "scientific-calculator",
  "fraction-calculator",
  "character-counter",
  "text-repeater",
  "binary-converter",
  "color-mixer",
  "css-transform-generator",
  "pregnancy-calculator",
  "pace-calculator",
  "bmr-calculator",
  "waist-to-hip-ratio-calculator",
  "water-intake-calculator",
  "calorie-deficit-calculator",
  "protein-calculator",
  "ideal-weight-calculator",
  "sleep-calculator",
  "1rm-calculator",
  "heart-rate-zone-calculator",
  "keto-calculator",
  "square-root-calculator",
  "mean-median-mode-calculator",
  "standard-deviation-calculator",
  "number-base-converter",
  "typing-speed-test",
  "ovulation-calculator",
  "weight-loss-calculator",
  "period-calculator",
  "refinance-calculator",
  "blood-alcohol-calculator",
  "square-footage-calculator",
  "concrete-calculator",
  "paint-calculator",
  "tile-calculator",
  "markup-calculator",
  "cd-calculator",
  "calorie-burn-calculator",
  "ohms-law-calculator",
  "future-value-calculator",
  "annuity-calculator",
  "emi-calculator",
  "walking-calorie-calculator",
  "debt-to-income-calculator",
  "jpg-to-pdf-converter",
  "merge-pdf",
  "compress-pdf",
  "split-pdf",
  "png-to-pdf-converter",
  "resume-builder",
  "video-compressor",
  "image-upscaler",
  "image-to-text",
  "pdf-to-word",
  "screen-recorder",
  "text-to-speech",
  "video-to-gif",
  "image-to-gif",
  "gif-to-images",
  "digital-signature",
  "meme-generator",
  "convert",
  "audio-converter",
  "video-converter",
  "document-converter",
  "image-watermark",
  "video-watermark",
  "emoji-picker",
  "video-transcript",
  "address-generator",
  "slideshow-maker",
  "video-trimmer",
  "video-joiner",
  "video-speed-changer",
  "video-subtitle-burner",
  "video-frame-extractor",
  "animated-webp",
  "apng-maker",
  "video-thumbnail",
  "claude-code-text-formatter",
  "doc-compare",
  "pdf-long-image",
  "tax-calculator",
  "obbba-tax-calculator",
  "electricity-cost-calculator",
  "medicaid-work-requirement-calculator",
  "whois-lookup",
  "ip-lookup",
  "car-lease-calculator",
  "income-percentile-calculator",
  "net-worth-percentile-calculator",
  "life-insurance-calculator",
  "home-affordability-calculator",
  "business-loan-calculator",
  "credit-score-simulator",
  "self-employment-tax-calculator",
  "car-loan-interest-deduction-calculator",
  "student-loan-tax-bomb-calculator",
  "trump-account-calculator",
  "mortgage-payoff-calculator",
  "child-support-calculator",
  "alimony-calculator",
  "personal-injury-calculator",
  "workers-comp-calculator",
  "dui-cost-calculator",
  "bankruptcy-means-test",
  "small-claims-court-calculator",
  "va-disability-calculator",
  "social-security-calculator",
  "medicare-cost-calculator",
  "chatgpt-ads-calculator",
  "save-vs-rap-calculator",
  "base64-to-image",
  "currency-converter",
  "image-to-relief",
  "id-photo-generator",
  "background-replace",
  "face-blur",
  "face-crop",
  "photo-colorize",
  "image-caption",
  "image-classify",
  "nsfw-detection",
  "image-denoise",
  "image-deblur",
  "unsharp-mask",
  "white-balance",
  "auto-contrast",
  "histogram-equalize",
  "hdr-tone-mapping",
  "dehaze",
  "image-rotate-flip",
  "image-negative",
  "image-pixelate",
  "image-oil-paint",
  "image-edge-detect",
  "image-rounded-corners",
  "image-border",
  "image-shadow",
  "image-histogram",
  "image-palette",
  "image-phash",
  "image-compare",
  "duplicate-finder",
  "rgb-channel-split",
  "image-web-optimizer",
  "batch-rename",
  "image-to-ascii",
  "css-sprite-generator",
  "og-image-generator",
  "blob-dataurl",
  "image-similarity",
  "image-stitcher",
  "pdf-to-jpg",
  "pdf-to-png",
  "docx-to-jpg",
  "docx-to-png",
  "commission-calculator",
  "depreciation-calculator",
  "lease-calculator",
  "overtime-calculator",
  "present-value-calculator",
  "rent-vs-buy-calculator",
  "dog-age-calculator",
];

// Keep in sync with the actual blog page directories: every listed slug must
// resolve to an existing page, otherwise search engines index 404s.
const blogSlugs = blogPostsMeta.map((p) => p.slug);

const staticPaths = ["", "/privacy", "/terms"];

export default function sitemap(): MetadataRoute.Sitemap {
  const base = "https://toolkitlife.com";
  const now = new Date();

  const entries: MetadataRoute.Sitemap = [];

  for (const locale of locales) {
    const prefix = `${base}/${locale}`;

    for (const path of staticPaths) {
      entries.push({
        url: `${prefix}${path}`,
        lastModified: now,
        changeFrequency: path === "" ? "weekly" : "yearly",
        priority: path === "" ? 1 : 0.5,
      });
    }

    entries.push({
      url: `${prefix}/blog`,
      lastModified: now,
      changeFrequency: "weekly",
      priority: 0.7,
    });

    for (const slug of blogSlugs) {
      entries.push({
        url: `${prefix}/blog/${slug}`,
        lastModified: now,
        changeFrequency: "monthly",
        priority: 0.6,
      });
    }

    for (const slug of tools) {
      entries.push({
        url: `${prefix}/tools/${slug}`,
        lastModified: now,
        changeFrequency: "monthly",
        priority: 0.8,
      });
    }
  }

  return entries;
}
